[package]
name = "quad-dshot-pio"
version = "0.1.1"
edition = "2021"

[dependencies]
dshot-encoder = {git = "https://github.com/peterkrull/dshot-encoder"}
rp2040-hal = "~0"
pio-proc = "~0.2"
pio = "~0.2"

